# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        exclude: docs/mkdocs.yml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
    -   id: clang-format
