# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  skip: [cmake-generate-compile-commands, clang-tidy]
  
repos:

  - repo: local
    hooks:
      - id: cmake-generate-compile-commands
        name: CMake configure (make compile_commands.json)        
        language: system
        entry: bash -c 'cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_DEBUG=ON -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=ON -DENABLE_CUDA=OFF -DENABLE_HIP=OFF'
        pass_filenames: false

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args:
          - -p=build
        files: ^Exec/Examples/EBGeometry_Shapes/
      
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
    - id: clang-format


