repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6 # pick the clang-format you want; match your devs
    hooks:
      - id: clang-format
        args: [--style=file]   # uses .clang-format at the repo root
        files: |
          (?x)^(
            Sources/.*\.(h|hh|hpp|hxx|inl)$|
            Exec/Tests/.*\.cpp$|
            Exec/Examples/EBGeometry_Shapes/.*\.cpp$
          )
