name: clang-tidy-review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ZedThree/clang-tidy-review@v0.21.0
        with:
          split_workflow: true
          cmake_command: >
            cmake -S . -B build
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DENABLE_TESTS=OFF
            -DENABLE_EXAMPLES=ON
            -DENABLE_CUDA=OFF
            -DENABLE_HIP=OFF
          build_dir: build
          include: >
            Exec/Examples/EBGeometry_Shapes/*.cpp
      - uses: ZedThree/clang-tidy-review/upload@v0.21.0
