name: clang-tidy-review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # clang-tidy build compile commands
      - uses: ZedThree/clang-tidy-review@v0.21.0
        with:
          split_workflow: true
          config_file : .clang-tidy
          cmake_command: >
            cmake -S . -B build
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DENABLE_TESTS=OFF
            -DENABLE_EXAMPLES=ON
            -DENABLE_CUDA=OFF
            -DENABLE_HIP=OFF
          build_dir: build

      # Upload artifact
      - uses: ZedThree/clang-tidy-review/upload@v0.21.0

      - if: steps.review.outputs.total_comments > 0
        run: exit 1


