name: clang-tidy-review
on: [pull_request]

permissions:
  contents: read
  pull-requests: read  # read only; comments happen in the "post" workflow

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ZedThree/clang-tidy-review@v0.21.0
        with:
          split_workflow: true
          cmake_command: >
            cmake -S . -B build
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF
            -DENABLE_CUDA=OFF -DENABLE_HIP=OFF
            -DEBGEOMETRY_TIDY_DUMMY=ON
          build_dir: build
          include: >
            EBGeometry.hpp, Source/**/*.hpp
          exclude: Exec/**
      - uses: ZedThree/clang-tidy-review/upload@v0.21.0
