name: clang-tidy-review

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clang-tidy
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  clang-tidy:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Tiny standalone CMake project so clang-tidy has a TU + compile_commands.json
      - name: Create stub project for headers
        run: |
          mkdir -p tools/ctu/src
          cat > tools/ctu/src/clang_tidy_all.cpp <<'EOF'
          #include "EBGeometry.hpp"
          EOF

          cat > tools/ctu/CMakeLists.txt <<'EOF'
          cmake_minimum_required(VERSION 3.15)
          project(clang_tidy_stub CXX)
          add_library(clang_tidy_headers OBJECT src/clang_tidy_all.cpp)

          # Include paths for your layout:
          # - repo root (EBGeometry.hpp)
          # - Source/ for the rest of the headers
          target_include_directories(clang_tidy_headers PRIVATE
            ${CMAKE_SOURCE_DIR}/../..          # repo root
            ${CMAKE_SOURCE_DIR}/../../Source   # headers under Source/
          )

          # Ensure C++20 for analysis
          target_compile_features(clang_tidy_headers PRIVATE cxx_std_20)

          # Add any needed defines here, e.g.:
          # target_compile_definitions(clang_tidy_headers PRIVATE EBG_ENABLE_SOMETHING=1)
          EOF

      - name: Configure & build stub (generates compile_commands.json)
        run: |
          cmake -S tools/ctu -B build/ctu -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build/ctu -j 2 || true

      - name: Clang-Tidy Review
        id: review
        uses: ZedThree/clang-tidy-review@4ea7f7b72e7e039588ef5e64de9a845e5a3f8db5 # v0.21.0
        with:
          build_dir: build/ctu
          clang_tidy_checks: ''        # use your .clang-tidy
          lgtm_comment_body: ''
          annotations: true

      - name: Upload clang-tidy fixes
        uses: ZedThree/clang-tidy-review/upload@4ea7f7b72e7e039588ef5e64de9a845e5a3f8db5 # v0.21.0

      - name: Fail if clang-tidy found issues
        if: ${{ steps.review.outputs.total_comments > 0 }}
        run: exit 1
