# .github/workflows/format-suggest.yml
name: clang-format (pre-commit → PR suggestions)

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python (pre-commit needs it)
        uses: actions/setup-python@39cd14951b08fb3e3ae6810f4f4c402a3a75b4f1 # v5.2.0

      - name: Run pre-commit (all hooks)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true  # don't fail yet; we want to capture diffs
      # At this point, any auto-fixes from hooks are applied in the workspace

      - name: Did formatting change anything?
        id: diffcheck
        run: |
          if ! git diff --quiet; then echo "changed=true" >> "$GITHUB_OUTPUT"; else echo "changed=false" >> "$GITHUB_OUTPUT"; fi

      - name: Post PR suggestions (reviewdog)
        if: steps.diffcheck.outputs.changed == 'true'
        uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
        with:
          tool_name: clang-format

      # Optional: make formatting a blocker
      # - name: Fail if formatting needed
      #   if: steps.diffcheck.outputs.changed == 'true'
      #   run: exit 1
