name: Linux GNU
permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, edited]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-code-format
  cancel-in-progress: true    

jobs:      
  linux-gnu:
    name: linux-gnu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        comp: [g++-9, g++-10, g++-11, g++-12]

    steps:
      - uses: actions/checkout@v4
      - name: Install compilers
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.comp }}

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          git checkout "v3.4.0"
          mkdir build && cd build
          cmake .. -DBUILD_TESTING=Off
          make -j $(nproc)
          sudo make install        

      - name: Configure
        working-directory: ${{ matrix.directory }}
        run: |
          cmake -S . -B build \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF \
          -DENABLE_TESTS=ON \
          -DENABLE_EXAMPLES=OFF \
          -DENABLE_CUDA=OFF \
          -DENABLE_HIP=OFF \
          
          cmake --build build -j2

      - name: Run tests
        working-directory: build/Exec/Tests
        run: |
          ctest -j2
