name: LOC Badge

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/badges/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Count LOC and build Shields JSON
        run: |
          mkdir -p .github/badges
          cloc . --json --quiet \
            --exclude-dir=.git,node_modules,dist,build,.next,out,coverage,vendor \
            > cloc.json

          python - << 'PY'
          import json, os
          data = json.load(open('cloc.json'))
          total = int(data.get('SUM', {}).get('code', 0))
          badge = {
            "schemaVersion": 1,
            "label": "lines of code",
            "message": f"{total:,}",
            "color": "blue"
          }
          with open(".github/badges/loc.json", "w") as f:
              json.dump(badge, f)
          PY

      - name: Commit badge JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update LOC badge [skip ci]"
          file_pattern: .github/badges/loc.json
