name: REUSE compliance

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, edited]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gnu
  cancel-in-progress: true    
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip "reuse==5.1.1"
      - run: reuse lint
